export const MESSAGE_TABLE: {
    [key: string]: string;
} = {
    "00":"Diagnosis ok",
    "01":"Engine temperature too high",
    "03":"Coolant circuit level too low",
    "04":"Check engine oil level",
    "05":"Engine oil pressure too low",
    "08":"Braking system faulty",
    "0A":"Air suspension ok (picture)",
    "0B":"Door, boot, bonnet and fuel tank open",
    "0D":"Tyre puncture(s) detected",
    "0F":"Risk of particle filter blocking",
    "11":"Suspension faulty: max.speed 90 km/h",
    "12":"Suspension faulty",
    "13":"Power steering faulty",
    "14":"10km/h!",
    "61":"Handbrake on",
    "62":"Handbrake off",
    "64":"Handbrake control faulty: auto handbrake activated",
    "67":"Brake pads worn",
    "68":"Handbrake faulty",
    "69":"Mobile deflector faulty",
    "6A":"ABS braking system faulty",
    "6B":"ESP / ASR system faulty",
    "6C":"Suspension faulty",
    "6D":"Power steering faulty",
    "6E":"Gearbox faulty",
    "6F":"Cruise (speed) control system faulty",
    "73":"Ambient brightness sensor faulty",
    "74":"Sidelamp bulb(s) faulty",
    "75":"Automatic headlamp adjustment faulty",
    "76":"Directional headlamps faulty",
    "79":"Active bonnet faulty",
    "7A":"Gearbox faulty",
    "7B":"Apply foot on brake and lever in position N",
    "7D":"Presence of water in diesel fuel filter",
    "7E":"Engine management system faulty",
    "7F":"Depollution system faulty",
    "81":"Particle filter additive level too low",
    "83":"Electronic anti-theft faulty",
    "86":"Right hand side door faulty",
    "87":"Left hand side door faulty",
    "89":"Space measuring system faulty",
    "8A":"Battery charge or electrical supply faulty",
    "8D":"Tyre pressure(s) too low",
    "92":"Warning message without text",
    "95":"Info message without text",
    "96":"Info message without text",
    "97":"Anti-wander system lane-crossing warning device faulty",
    "9D":"Foglamp bulb(s) faulty",
    "9E":"Direction indicator(s) faulty",
    "A0":"Sidelamp bulb(s) faulty",
    "A1":"Parking lamps active",
    "CD":"Cruise control not possible: speed too low",
    "CE":"Control activation not possible: enter the speed",
    "D1":"Active bonnet deployed",
    "D2":"Front seat belts not fastened",
    "D3":"Rear right hand passenger seat belts fastened",
    "D7":"Place automatic gearbox in position P",
    "D8":"Risk of ice",
    "D9":"Handbrake!",
    "DE":"Door, boot, bonnet and fuel tank open",
    "DF":"Screen wash fluid level too low",
    "E0":"Fuel level too low",
    "E1":"Fuel circuit deactivated",
    "E3":"Remote control battery flat",
    "E4":"Check and re-initialise tyre pressure",
    "E5":"Tyre pressure(s) not monitored",
    "E7":"High speed, check tyre pressures correct",
    "E8":"Tyre pressure(s) too low",
    "EA":"Hands-free starting system faulty",
    "EB":"Starting phase has failed (consult handbook)",
    "EC":"Prolonged starting in progress",
    "ED":"Starting impossible: unlock the steering",
    "EF":"Remote control detected",
    "F0":"Diagnosis in progress...",
    "F1":"Diagnosis completed",
    "F7":"Rear LH passenger seatbelt unfastened",
    "F8":"Rear center passenger seatbelt unfastened",
    "F9":"Rear RH passenger seatbelt unfastened",
    "FF":"No message"
}